### GET / Hola Mundo
GET http://localhost:1234/

### POST / 405
POST http://localhost:1234/

### Petición imagen
GET http://localhost:1234/logo.webp


### POST
POST http://localhost:1234/contacto
Content-Type: application/json

{
  "name": "ditto",
  "email": "normal",
  "message": "transform"
}

### PUT / 405
PUT http://localhost:1234/contacto
Content-Type: application/json

{
  "name": "ditto",
  "email": "normal",
  "message": "transform"
}

### POST 404
POST http://localhost:1234/404

### GET 401
GET http://localhost:1234/dfskdjghfksjd